permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Pew Pew"
  description: |
    A Star Wars themed merchandise site that jedi and sith alike can buy various apparel and collectibles.
    Will you follow the light or be consumed by the dark?
  colors:
    sidebar: "--color-primary"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary-opposite"
      brand.colors: "--color-primary-opposite"
      form.search: "--color-primary"
  rationales:
    typefaces.primary: |
      Verdana was selected becasue it is a clean, simple font. Verdana is to be used for all text with varying weights and case.
    colors.primary: |
      The primary colours represent the galaxy above. They should be used for the text and in backgrounds.
    colors.secondary: |
      The secondary colour is more vibrant and bright, and should be used for buttons and in some hover situations.
    colors.accent: |
      The accent colour is another vibrant and bright colour, and should be used in most hover situations.

      The colours, alert, alert-light, and alert-dark, are used only in the error message and should not be used anywhere else.
    colors.neutral: |
      The neutral colours should be used to accent cards and other elements.
  layouts:
    default: |
      The default layout should be used for alomst every page, it includes the website’s main header and footer.
  collections:
    products:
      output: true
  defaults:
    - scope:
        path: _product
      values:
        layout: product
