title: "Product Sections"
description: |
  The product sections are all the elements found on the product details pages. These elements should only be used on the product details pages. The information contained describes all the deatils about a product and should be used in conjunction with a photo array. The photo array should always placed on the left, while the product details on the right.

patterns:
  photo-array:
    title: "Photo Array"
    description: |

  product-details:
    title: "Product Details"
    description: |
      This is the product description section.
    fields:
      - name: prod-name
        type: string
        example: "Stormtrooper Bobble Head"
      - name: prod-price
        type: value
        example: "14.99"
      - name: prod-desc
        type: string
        example: ""
      - name: prod-deets
        type: string
        example: "50% cotton / 50% polyester"
      - name: prod-ship
        type: string
        example: "Please allow 2-3 weeks for delivery."
