title: "Product Sections"
description: |
  The product sections are all the elements found on the product details pages. These elements should only be used on the product details pages. The information contained describes all the deatils about a product and should be used in conjunction with a photo array. The photo array should always placed on the left, while the product details on the right.

patterns:
  photo-array:
    title: "Photo Array"
    description: |
      This is the photo array section. It is to only be used on the product details pages, and should always be located to the left of the product details section.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
  product-details:
    title: "Product Details"
    description: |
      This is the product details section. It is to only be used on the product details pages, and should always be located to the right of a photo array.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
