title: "Sections"
description: |
  The sections includes various groupings of information. The image sections and the text section should be used on the main page. The item summary and order summary sections should only be used on the checkout page.

patterns:
  full-img-section:
    title: "Image Section"
    description: |
      This is a full image section. It is used to promote sales and new items to the website. This image section should be used on the main page and the product should be located to the left of the image.
    fields:
      - name: title
        type: string
        example: "Select collectibles up to 50% off!"
      - name: details
        type: string
        example: "Get them now, sale ends May 4th"
      - name: image
        type: image
        example: "product-stpf.jpg"
  half-img-section:
    title: "Half Image Section"
    description: |
      This is a half image section. It is used to promote sales and new items to the website, and should be used on the main page.
    fields:
      - name: title
        type: string
        example: "Select collectibles up to 50% off!"
      - name: details
        type: string
        example: "Get them now, sale ends May 4th"
      - name: image
        type: image
        example: "product-stpf.jpg"
  text-section:
    title: "Text Section"
    description: |
      This is a text section. It is meant for multiple lines of text, and is used on pages such as an about page.
    fields:
      - name: title
        type: string
        example: "About"
      - name: details
        type: string
        example: "A Star Wars themed merchandise site that jedi and sith alike can buy various apparel and collectibles. Will you follow the light or be consumed by the dark?"
  item-summary:
    title: "Item Summary"
    description: |

  order-summary:
    title: "Order Summary"
    description: |
