title: "Cards"
description: |
  Cards should be used for situations where text is to enhanced with images and for all products on pages other than their respective info page.

patterns:
  product-cards:
    title: "Product Card"
    description: |
      This is the standard product card. Each card should contain a product image, product title, and price.
    padding: 2em
    width: 25em
    fields:
      - name: prod-card
        type: object
        data:
          source: "site.products[0]"
          type: Product
  sale-card:
    title: "Sale Card"
    description: |
      This is a sale product card and is used for item that go on sale. Each card must contain a product image, product title, and original price and sale price.
    padding: 2em
    width: 25em
    fields:
      - name: title
        type: string
        example: "Bantha Fodder Sweatshirt"
      - name: term
        type: value
        example: "24.99"
      - name: price
        type: value
        example: "15.99"
      - name: image
        type: image
        example: "sweater-grey.jpg"
      - name: icon
        type: image
        example: "icons.svg#sale-icon"
      - name: alt
        type: string
        example: "An image of a grey long-sleeve sweatshirt with a black design of a Bantha and reads 'Bantha Fodder'."
      - name: url
        type: url
        example: "/products-1.html"
  new-card:
    title: "New Item Card"
    description: |
      This is a new product card and is used for new items added to the shop. Each card must contain a product image, product title, and original price and sale price.
    padding: 2em
    width: 25em
    fields:
      - name: title
        type: string
        example: "Han Shot First Tee"
      - name: term
        type: value
        example: "22.99"
      - name: image
        type: image
        example: "t-black-1.jpg"
      - name: icon
        type: image
        example: "icons.svg#new-icon"
      - name: alt
        type: string
        example: "An image of a black t-shirt with the design 'Han Shot First' where 'Shot' is replaced by an illustration of Han's blaster with a blaster bolt."
      - name: url
        type: url
        example: "/products-1.html"
  icon-cards:
    title: "Icon Card"
    description: |
      This is an icon card. It is used to describe some of the feature such as fast shipping.
    padding: 2em
    fields:
      - name: title
        type: string
        example: "Fast Shipping"
      - name: details
        type: string
        example: "Delivered in less than 12 parsecs"
      - name: image
        type: image
        example: "icons.svg#cart-icon"
  category-card:
    title: "Category Card"
    description: |
      This is a category card and is used to link to item categories such as men, womens, sale, shirts, etc.
    padding: 2em
    width: 25em
    fields:
      - name: catcard
        type: object
        data:
          source: ""
          type: Product
