title: "Navigation"
description: |
  These are all the types of navigations found on the site, including the main navigation, as well as the navigations that are not part of the header or footer.

patterns:
  main-nav:
    title: "Main Navigation"
    description: |

  page-nav:
    title: "Page Navigation"
    description: |
      This is the page navigation. This should be used on the main products pages and the category pages, or any page that showcases a list of individual products in cards. It should be located at the bottom right of the page above the footer.
    fields:
      - name: arrow-l
        type: image
        example: "icons.svg#left-arrow"
      - name: arrow-r
        type: image
        example: "icons.svg#right-close-arrow"

  product-filters:
    title: "Product Filters"
    description: |

    fields:
      - name: icon
        type: image
        example: "icons.svg#right-close-arrow"
  social-nav:
    title: "Social Media Navigation"
    description: |
      This is the social navigation buttons. These buttons link to external sites for the social media pages. It is used in the footer only.
    fields:
      - name: facebook
        type: image
        example: "icons.svg#facebook"
      - name: twitter
        type: image
        example: "icons.svg#twitter"
      - name: pinterest
        type: image
        example: "icons.svg#pinterest"
