title: "Navigation"
description: |
  These are all the types of navigations found on the site, including the main navigation, as well as the navigations that are not part of the header or footer.

patterns:
  main-nav:
    title: "Main Navigation"
    description: |

  page-nav:
    title: "Page Navigation"
    description: |

    fields:
      - name: arrow-l
        type: image
        example: "icons.svg#left-arrow"
      - name: arrow-r
        type: image
        example: "icons.svg#right-close-arrow"

  product-filters:
    title: "Product Filters"
    description: |

  social-nav:
    title: "Social Media Navigation"
    description: |

    fields:
      - name: facebook
        type: image
        example: "icons.svg#facebook"
      - name: twitter
        type: image
        example: "icons.svg#twitter"
      - name: pinterest
        type: image
        example: "icons.svg#pinterest"
