title: "Forms"
description: |
  Forms are used in situations with a ‘submit’ button. Each field should have a unique ‘id’ and ‘for’ in the form it is placed.

patterns:
  basic-form:
    title: "Basic Form Field"
    description: |
      This is the basic form field. It is meant for single lines of text, and can be used where necessary. This field by default is not required, which can be used for optional fields such as ‘address line 2’.
    width: 38em
    fields:
      - name: title
        type: string
        example: "Address 2"
      - name: id
        type: string
        example: "address-2"
      - name: type
        type: string
        example: "text"
      - name: placeholder
        type: string
        example: ""
  required-basic:
    title: "Basic Required Form Field"
    description: |
      This is the basic required form field. It is meant for single lines of text, and should be used for forms found in the checkout, sign up, and login pages. This field by default is required and inlcuded an error message when fields are submitted without being filled.
    width: 38em
    fields:
      - name: title
        type: string
        example: "Last Name"
      - name: id
        type: string
        example: "last-name"
      - name: details
        type: string
        example: "a last name"
      - name: error
        type: string
        example: "last-name-error"
      - name: type
        type: string
        example: "text"
      - name: placeholder
        type: string
        example: ""
  basic-checkbox:
    title: "Basic Checkbox"
    description: |
      This is the standard checkbox.This checkbox by default is not required, which can be used for optional elements such as agreeing to receive emails, offers, and other non-contract agreements.
    width: 38em
    fields:
      - name: label
        type: string
        example: "Would you like to receive promotional offers?"
      - name: id
        type: string
        example: "promo-offers"
  required-checkbox:
    title: "Basic Required Checkbox"
    description: |
      This is the basic required checkbox. This checkbox by default is required, which can be used for agreeing to the terms of service.
    width: 38em
    fields:
      - name: label
        type: string
        example: "Agree to Terms and Servies"
      - name: id
        type: string
        example: "tos"
      - name: details
        type: string
        example: "You must agree to the Terms and Services"
      - name: error
        type: string
        example: "tos-error"
  search:
    title: "Search Field"
    description: |
      This is the search field. It is used only in the header on medium and large screens on dark backgrounds.
    width: 20em
