title: "Forms"
description: |
  Forms are used in situations with a ‘submit’ button. Each field should have a unique ‘id’ and ‘for’ in the form it is placed.

patterns:
  basic-form:
    title: "Basic Form Field"
    description: |
      This is the basic form field. It is meant for single lines of text, and can be used where necessary. This field by default is not required, which can be used for optional fields such as ‘address line 2’.
    width: 38em
    fields:
      - name: title
        type: string
        example: "Address 2"
      - name: id
        type: string
        example: "address-2"
      - name: type
        type: string
        example: "text"
      - name: placeholder
        type: string
        example: ""
  required-basic:
    title: "Basic Required Form Field"
    description: |
      This is the basic required form field. It is meant for single lines of text, and should be used for forms found in the checkout, sign up, and login pages. This field by default is required and inlcuded an error message when fields are submitted without being filled.
    width: 38em
    fields:
      - name: title
        type: string
        example: "Last Name"
      - name: id
        type: string
        example: "last-name"
      - name: details
        type: string
        example: "a last name"
      - name: error
        type: string
        example: "last-name-error"
      - name: type
        type: string
        example: "text"
      - name: placeholder
        type: string
        example: ""
  basic-checkbox:
    title: "Basic Checkbox"
    description: |
      This is the standard checkbox.This checkbox by default is not required, which can be used for optional elements such as agreeing to receive emails, offers, and other non-contract agreements.
    width: 38em
    fields:
      - name: label
        type: string
        example: "Would you like to receive promotional offers?"
      - name: id
        type: string
        example: "promo-offers"
  required-checkbox:
    title: "Basic Required Checkbox"
    description: |
      This is the basic required checkbox. This checkbox by default is required, which can be used for agreeing to the terms of service.
    width: 38em
    fields:
      - name: label
        type: string
        example: "Agree to Terms and Servies"
      - name: id
        type: string
        example: "tos"
      - name: details
        type: string
        example: "You must agree to the Terms and Services"
      - name: error
        type: string
        example: "tos-error"
  radio:
    title: "Basic Radio Button"
    description: |
      This is the basic radio button. This radio button by default is required, which can be used for determining yes or no questions, or any question invloving multiple answer choices but only one option to pick.
    width: 38em
    fields:
      - name: legend
        type: string
        example: "Choose a Delivery Method"
      - name: id1
        type: string
        example: "std-ship"
      - name: id2
        type: string
        example: "2d-ship"
      - name: id3
        type: string
        example: "1d-ship"
      - name: name
        type: string
        example: "ship"
      - name: label1
        type: string
        example: "Standard Shipping"
      - name: label2
        type: string
        example: "2-Day Express Shipping"
      - name: label3
        type: string
        example: "1-Day Express Shipping"
      - name: price1
        type: number
        example: "5.99"
      - name: price2
        type: number
        example: "8.99"
      - name: price3
        type: number
        example: "11.99"
      - name: description1
        type: string
        example: "Normally ships in 4–5 business days, unless otherwise noted."
      - name: description2
        type: string
        example: "Normally ships in 2 business days, unless otherwise noted."
      - name: description3
        type: string
        example: "Normally ships in 1 business day, unless otherwise noted."
      - name: details
        type: string
        example: "You must select a delivery method"
      - name: error
        type: string
        example: "ship-error"
  select-region:
    title: "Region/Country Selection Field"
    description: |
      This is the region/country selection field. This field by default is required, and is found on the shipping and payment forms.
    width: 38em
    fields:
      - name: id
        type: string
        example: "country"
      - name: label
        type: string
        example: "Country/Region"
      - name: details
        type: string
        example: "You must select a country or region"
      - name: error
        type: string
        example: "region-error"
  select-size:
    title: "Size Selection Field"
    description: |
      This is the size selection field. This field by default is required, and is found on the product pages.
    width: 8em
    fields:
      - name: id
        type: string
        example: "size"
      - name: label
        type: string
        example: "Size"
      - name: details
        type: string
        example: "You must select a size"
      - name: error
        type: string
        example: "size-error"
  select-quantity:
    title: "Quantity Selection Field"
    description: |
      This is the quantity selection field. This field by default is required, and is found on the product pages.
    width: 8em
    fields:
      - name: id
        type: string
        example: "quant"
      - name: title
        type: string
        example: "Quantity"
      - name: type
        type: string
        example: "number"
      - name: details
        type: string
        example: "Please select a quantity"
      - name: error
        type: string
        example: "quant-error"
  search:
    title: "Search Field"
    description: |
      This is the search field. It is used only in the header on medium and large screens on dark backgrounds.
    width: 20em
