title: "Banners"
description: |
  Banners are used to delineate the various sections, promote site-wide deals, and call-to-actions.

patterns:
  basic:
    title: "Sectional Banner"
    description: |
      A sectional banner is used to separate the various sections on the website. For this banner, no image is to be used.
    fields:
      - name: title
        type: string
        example: "New Arrivals"
  call-to-action:
    title: "Call To Action Banner"
    description: |
      A call to action banner is used on the main page only. It is meant to showcase new arrlivals, sales, and the top selling products.
    fields:
      - name: title
        type: string
        example: "Calling All Scavengers!"
      - name: details
        type: string
        example: "Come raid our new stock."
      - name: button_title
        type: string
        example: "Buy Now"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
  promotional-banner:
    title: "Promotional Banner"
    description: |
      The promotional banner is used to promote site wide sales and new items.
    fields:
      - name: title
        type: string
        example: "All stickers are 25% off!"
      - name: details
        type: string
        example: "Get some now, offer lasts until May 4th."
      - name: href
        type: url
        example: "/products/"
  checkout-banner:
    title: "Checkout Banner"
    description: |
      This is a checkout banner. It is used on the checkout page to section the forms into shipping information and payment information.
    fields:
      - name: num
        type: string
        example: "1"
      - name: title
        type: string
        example: "Shipping Information"
